function generateAnalysis(ticker,indData,sr,priceAction){const{rsi,macd,bb,stoch,atr,obv,volRatio,ema20,ema50,lastClose}=indData;let score=0,signals=[];
let ms=0;if(macd.histogram>0&&macd.macd<0){ms=0.9;signals.push({text:`MACD bullish crossover below zero — histogram just turned positive (${macd.histogram.toFixed(3)}). Early reversal signal.`,type:'bull'});}else if(macd.histogram<0&&macd.histogram>macd.signal){ms=0.6;signals.push({text:`MACD bearish momentum fading — histogram (${macd.histogram.toFixed(3)}) narrowing toward zero.`,type:'bull'});}else if(macd.histogram<0&&macd.macd>0){ms=-0.9;signals.push({text:`MACD bearish crossover above zero — histogram just turned negative (${macd.histogram.toFixed(3)}).`,type:'bear'});}else if(macd.histogram>0&&macd.histogram<macd.signal){ms=-0.6;signals.push({text:`MACD bullish momentum fading — histogram (${macd.histogram.toFixed(3)}) shrinking.`,type:'bear'});}
score+=ms*0.30;
let ss=0;if(stoch.k<25&&stoch.k>stoch.d){ss=1.0;signals.push({text:`Stochastic bullish cross from oversold (%K:${stoch.k.toFixed(0)} above %D:${stoch.d.toFixed(0)}) — strongest short-term buy signal.`,type:'bull'});}else if(stoch.k<25){ss=0.4;signals.push({text:`Stochastic oversold (%K:${stoch.k.toFixed(0)}) — cross not yet confirmed.`,type:'bull'});}else if(stoch.k>75&&stoch.k<stoch.d){ss=-1.0;signals.push({text:`Stochastic bearish cross from overbought (%K:${stoch.k.toFixed(0)} below %D:${stoch.d.toFixed(0)}) — strongest short-term sell signal.`,type:'bear'});}else if(stoch.k>75){ss=-0.4;signals.push({text:`Stochastic overbought (%K:${stoch.k.toFixed(0)}) — bearish cross not yet confirmed.`,type:'bear'});}else if(stoch.k>50&&stoch.k>stoch.d){ss=0.2;}else if(stoch.k<50&&stoch.k<stoch.d){ss=-0.2;}
score+=ss*0.25;
let rs=0;if(rsi<25){rs=1.0;signals.push({text:`RSI at ${rsi.toFixed(1)} — extreme oversold. Sellers statistically depleted.`,type:'bull'});}else if(rsi<35){rs=0.7;signals.push({text:`RSI at ${rsi.toFixed(1)} — deeply oversold. Watch for bounce candle.`,type:'bull'});}else if(rsi>75){rs=-1.0;signals.push({text:`RSI at ${rsi.toFixed(1)} — extreme overbought. Buyers statistically depleted.`,type:'bear'});}else if(rsi>65){rs=-0.7;signals.push({text:`RSI at ${rsi.toFixed(1)} — overbought. Upside tiring.`,type:'bear'});}
score+=rs*0.20;
let bs=0;if(bb.pctB<0.05){bs=1.0;signals.push({text:`Price at Bollinger lower band (%B:${(bb.pctB*100).toFixed(0)}%) — mean reversion zone.`,type:'bull'});}else if(bb.pctB<0.15){bs=0.7;signals.push({text:`Price near Bollinger lower band (%B:${(bb.pctB*100).toFixed(0)}%).`,type:'bull'});}else if(bb.pctB>0.95){bs=-1.0;signals.push({text:`Price at Bollinger upper band (%B:${(bb.pctB*100).toFixed(0)}%) — overextended.`,type:'bear'});}else if(bb.pctB>0.85){bs=-0.7;signals.push({text:`Price near Bollinger upper band (%B:${(bb.pctB*100).toFixed(0)}%).`,type:'bear'});}
score+=bs*0.15;
let es=0;if(lastClose>ema20&&lastClose<ema20*1.02&&ema20<ema50){es=0.8;signals.push({text:`Price just reclaimed EMA20 ($${ema20.toFixed(2)}) from below — early reversal.`,type:'bull'});}else if(lastClose>ema50&&lastClose<ema50*1.02&&ema20<ema50){es=1.0;signals.push({text:`Price just reclaimed EMA50 ($${ema50.toFixed(2)}) — major reversal signal.`,type:'bull'});}else if(lastClose<ema20&&lastClose>ema20*0.98&&ema20>ema50){es=-0.8;signals.push({text:`Price just lost EMA20 ($${ema20.toFixed(2)}) — early bearish reversal.`,type:'bear'});}else if(lastClose<ema50&&lastClose>ema50*0.98&&ema20>ema50){es=-1.0;signals.push({text:`Price broke below EMA50 ($${ema50.toFixed(2)}) — major bearish signal.`,type:'bear'});}
score+=es*0.10;
const va=volRatio>1.5?1.3:volRatio>1.2?1.1:volRatio<0.7?0.85:1.0;score=Math.max(-1,Math.min(1,score*va));
if(priceAction&&typeof priceAction.score==='number'){score=Math.max(-1,Math.min(1,score*0.75+Math.max(-1,Math.min(1,priceAction.score))*0.25));signals=[...priceAction.signals,...signals];}
const cc=s=>Math.min(92,Math.round(20+Math.abs(s)*72));let bias,biasClass,confidence,prediction;
if(score>0.2){bias='BULLISH';biasClass='bull';confidence=cc(score);prediction=score>0.6?'STRONG REVERSAL UP LIKELY':score>0.35?'UPSIDE MOVE BUILDING':'DEVELOPING SETUP';}else if(score<-0.2){bias='BEARISH';biasClass='bear';confidence=cc(score);prediction=score<-0.6?'STRONG REVERSAL DOWN LIKELY':score<-0.35?'DOWNSIDE MOVE BUILDING':'DEVELOPING SETUP';}else{bias='NEUTRAL';biasClass='neutral';confidence=cc(score);prediction='NO CLEAR SETUP — WAIT FOR SIGNAL';}
const upT=lastClose+atr*(score>0?2:1),downT=lastClose-atr*(score<0?2:1),stop=bias==='BULLISH'?lastClose-atr*1.5:lastClose+atr*1.5;
let srt='';if(sr.resistance.length)srt+=`\nKey resistance: ${sr.resistance.map(r=>'$'+r.price.toFixed(2)).join(', ')}`;if(sr.support.length)srt+=`\nKey support: ${sr.support.map(s=>'$'+s.price.toFixed(2)).join(', ')}`;
const top=signals.slice(0,5);let analysis=confidence>=80?`\u26a1 HIGH CONVICTION \u2014 ${prediction}\n\n`:'';analysis+=`SIGNAL BREAKDOWN:\n`;top.forEach(s=>{analysis+=`\u2022 ${s.text}\n`;});if(srt)analysis+=`\n${srt}`;analysis+=`\n\nRISK FACTORS:\n`;if(bias==='BULLISH'){analysis+=`\u2022 Failure to hold $${(lastClose-atr).toFixed(2)} invalidates setup\n\u2022 Low volume on bounce = weak reversal\n\u2022 Broader market selloff could override`;}else if(bias==='BEARISH'){analysis+=`\u2022 Reclaim of $${(lastClose+atr).toFixed(2)} invalidates setup\n\u2022 Low volume on drop = weak move\n\u2022 Positive catalyst could reverse quickly`;}else{analysis+=`\u2022 Breakout above $${(lastClose+atr*0.8).toFixed(2)} triggers bull setup\n\u2022 Break below $${(lastClose-atr*0.8).toFixed(2)} triggers bear setup\n\u2022 No edge now — wait for signal`;}
return{bias,biasClass,confidence,prediction,analysis,upTarget:upT,downTarget:downT,stopLoss:stop,score,keySignals:signals};}

function generateContinuationAnalysis(ticker,indData,sr,priceAction){const{rsi,macd,bb,stoch,atr,obv,volRatio,ema20,ema50,lastClose}=indData;let score=0,signals=[];
let es=0;const slope=ema20>ema50*1.005,near20=lastClose>ema20*0.98&&lastClose<ema20*1.03;if(lastClose>ema20&&ema20>ema50&&slope){es=1.0;if(near20)signals.push({text:`Price pulled back to EMA20 ($${ema20.toFixed(2)}) in uptrend — classic buy-the-dip zone.`,type:'bull'});else signals.push({text:`Bull structure: EMA20 ($${ema20.toFixed(2)}) > EMA50 ($${ema50.toFixed(2)}) with upward slope.`,type:'bull'});}else if(lastClose<ema20&&ema20<ema50){es=-1.0;signals.push({text:`Downtrend intact: EMA20 ($${ema20.toFixed(2)}) < EMA50 ($${ema50.toFixed(2)}).`,type:'bear'});}else if(lastClose>ema20&&ema20<ema50){es=0.2;signals.push({text:`Early uptrend but EMA50 ($${ema50.toFixed(2)}) still overhead.`,type:'neutral'});}else{es=-0.3;signals.push({text:`Trend weakening — price below EMA20 ($${ema20.toFixed(2)}).`,type:'bear'});}
score+=es*0.30;
let ms=0;if(macd.histogram>0&&macd.histogram>macd.signal*0.8&&macd.macd>0){ms=1.0;signals.push({text:`MACD confirming bull continuation — histogram positive and expanding.`,type:'bull'});}else if(macd.histogram>0&&macd.macd>0){ms=0.6;signals.push({text:`MACD supporting uptrend — histogram positive.`,type:'bull'});}else if(macd.histogram>0&&macd.macd<0){ms=0.2;signals.push({text:`MACD improving but still below zero.`,type:'neutral'});}else if(macd.histogram<0&&macd.macd<0&&macd.histogram<macd.signal){ms=-1.0;signals.push({text:`MACD confirming bear continuation — histogram expanding below zero.`,type:'bear'});}else if(macd.histogram<0&&macd.macd<0){ms=-0.6;signals.push({text:`MACD supporting downtrend.`,type:'bear'});}else{ms=-0.3;signals.push({text:`MACD momentum fading.`,type:'bear'});}
score+=ms*0.25;
const inBull=ema20>ema50;let rs=0;if(rsi>=50&&rsi<=65){rs=1.0;signals.push({text:`RSI at ${rsi.toFixed(1)} — in the bull momentum zone (50-65).`,type:'bull'});}else if(rsi>65&&rsi<=75){rs=0.4;signals.push({text:`RSI at ${rsi.toFixed(1)} — elevated but trend can stay here.`,type:'neutral'});}else if(rsi>=35&&rsi<50){if(inBull){rs=0.3;signals.push({text:`RSI at ${rsi.toFixed(1)} — healthy pullback in bull trend.`,type:'bull'});}else{rs=-1.0;signals.push({text:`RSI at ${rsi.toFixed(1)} — bear momentum zone with bearish EMA structure.`,type:'bear'});}}else if(rsi>75){rs=-0.5;signals.push({text:`RSI at ${rsi.toFixed(1)} — overbought, continuation risky.`,type:'bear'});}else{rs=0.3;signals.push({text:`RSI at ${rsi.toFixed(1)} — oversold, bear continuation risky.`,type:'neutral'});}
score+=rs*0.20;
let os=0;if(obv.trend==='RISING'&&volRatio>1.0){os=1.0;signals.push({text:`OBV rising with solid volume — institutions participating.`,type:'bull'});}else if(obv.trend==='RISING'){os=0.5;signals.push({text:`OBV trending up — accumulation ongoing.`,type:'bull'});}else if(obv.trend==='FALLING'&&volRatio>1.0){os=-1.0;signals.push({text:`OBV falling on solid volume — institutional distribution.`,type:'bear'});}else{os=-0.5;}
score+=os*0.15;
const bw=bb.bandwidth;let bs=0;if(bw>0.08&&score>0){bs=1.0;signals.push({text:`Bollinger Bands expanding (${(bw*100).toFixed(1)}%) — trend strengthening.`,type:'bull'});}else if(bw>0.08&&score<0){bs=-1.0;signals.push({text:`Bollinger Bands expanding in downtrend — sell-off accelerating.`,type:'bear'});}else if(bw<0.04){bs=-0.5;signals.push({text:`Bollinger Bands tight (${(bw*100).toFixed(1)}%) — consolidating.`,type:'neutral'});}
score+=bs*0.10;
if(priceAction&&typeof priceAction.score==='number'){score=Math.max(-1,Math.min(1,score*0.75+Math.max(-1,Math.min(1,priceAction.score))*0.25));signals=[...priceAction.signals,...signals];}
const cc=s=>Math.min(92,Math.round(20+Math.abs(s)*72));let bias,biasClass,confidence,prediction;
if(score>0.25){bias='BULLISH';biasClass='bull';confidence=cc(score);prediction=score>0.6?'STRONG UPTREND — HIGH CONTINUATION ODDS':score>0.4?'UPTREND INTACT — BUY DIPS':'DEVELOPING SETUP';}else if(score<-0.25){bias='BEARISH';biasClass='bear';confidence=cc(score);prediction=score<-0.6?'STRONG DOWNTREND — CONTINUATION LIKELY':score<-0.4?'DOWNTREND INTACT — SELL RALLIES':'DEVELOPING SETUP';}else{bias='NEUTRAL';biasClass='neutral';confidence=cc(score);prediction='NO CLEAR TREND — WAIT FOR STRUCTURE';}
const upT=lastClose+atr*2,downT=lastClose-atr*2,stop=bias==='BULLISH'?Math.max(lastClose-atr*1.5,ema20*0.99):lastClose+atr*1.5;
let srt='';if(sr.resistance.length)srt+=`\nKey resistance: ${sr.resistance.map(r=>'$'+r.price.toFixed(2)).join(', ')}`;if(sr.support.length)srt+=`\nKey support: ${sr.support.map(s=>'$'+s.price.toFixed(2)).join(', ')}`;
const top=signals.slice(0,5);let analysis=confidence>=80?`\u26a1 HIGH CONVICTION \u2014 ${prediction}\n\n`:'';analysis+=`TREND SIGNALS:\n`;top.forEach(s=>{analysis+=`\u2022 ${s.text}\n`;});if(srt)analysis+=`\n${srt}`;analysis+=`\n\nRISK FACTORS:\n`;if(bias==='BULLISH'){analysis+=`\u2022 Loss of EMA20 ($${ema20.toFixed(2)}) invalidates bull continuation\n\u2022 RSI above 75 = exhaustion, reduce position\n\u2022 MACD histogram shrinking = early exit warning`;}else if(bias==='BEARISH'){analysis+=`\u2022 Reclaim of EMA20 ($${ema20.toFixed(2)}) invalidates bear continuation\n\u2022 RSI below 30 = oversold bounce risk\n\u2022 MACD histogram narrowing = downside fading`;}else{analysis+=`\u2022 No trend to trade — low edge\n\u2022 Wait for EMA20/50 to align\n\u2022 Bollinger squeeze breakout will define next trend`;}
return{bias,biasClass,confidence,prediction,analysis,upTarget:upT,downTarget:downT,stopLoss:stop,score,keySignals:signals};}