// ===== TECHNICAL CALCULATIONS =====
function calcEMA(data,period){const k=2/(period+1);let ema=[data[0]];for(let i=1;i<data.length;i++)ema.push(data[i]*k+ema[i-1]*(1-k));return ema;}
function calcRSI(closes,period=14){let gains=[],losses=[];for(let i=1;i<closes.length;i++){const d=closes[i]-closes[i-1];gains.push(d>0?d:0);losses.push(d<0?-d:0);}if(gains.length<period)return null;let ag=gains.slice(0,period).reduce((a,b)=>a+b,0)/period,al=losses.slice(0,period).reduce((a,b)=>a+b,0)/period;for(let i=period;i<gains.length;i++){ag=(ag*(period-1)+gains[i])/period;al=(al*(period-1)+losses[i])/period;}if(al===0)return 100;return 100-(100/(1+ag/al));}
function calcMACD(closes){const e12=calcEMA(closes,12),e26=calcEMA(closes,26),ml=e12.map((v,i)=>v-e26[i]),sig=calcEMA(ml.slice(ml.length-20),9),lm=ml[ml.length-1],ls=sig[sig.length-1];return{macd:lm,signal:ls,histogram:lm-ls};}
function calcBollinger(closes,period=20){const sl=closes.slice(-period),mean=sl.reduce((a,b)=>a+b,0)/period,std=Math.sqrt(sl.map(v=>(v-mean)**2).reduce((a,b)=>a+b,0)/period),upper=mean+2*std,lower=mean-2*std,last=closes[closes.length-1];return{upper,lower,middle:mean,pctB:(last-lower)/(upper-lower),bandwidth:(upper-lower)/mean};}
function calcStochastic(highs,lows,closes,period=14){const sh=highs.slice(-period),sl=lows.slice(-period),hi=Math.max(...sh),lo=Math.min(...sl),last=closes[closes.length-1],k=((last-lo)/(hi-lo))*100,ks=[];for(let i=0;i<3;i++){const h2=Math.max(...highs.slice(-(period+i),highs.length-i||undefined)),l2=Math.min(...lows.slice(-(period+i),lows.length-i||undefined)),c2=closes[closes.length-1-i];ks.push(((c2-l2)/(h2-l2))*100);}return{k,d:ks.reduce((a,b)=>a+b,0)/3};}
function calcATR(highs,lows,closes,period=14){const trs=[];for(let i=1;i<closes.length;i++)trs.push(Math.max(highs[i]-lows[i],Math.abs(highs[i]-closes[i-1]),Math.abs(lows[i]-closes[i-1])));return trs.slice(-period).reduce((a,b)=>a+b,0)/period;}
function calcOBV(closes,volumes){let obv=0,arr=[0];for(let i=1;i<closes.length;i++){if(closes[i]>closes[i-1])obv+=volumes[i];else if(closes[i]<closes[i-1])obv-=volumes[i];arr.push(obv);}const r=arr.slice(-10);return{obv,trend:r[r.length-1]>r[0]?'RISING':'FALLING'};}
function findSupportResistance(highs,lows,closes,n=5){const levels=[];for(let i=n;i<closes.length-n;i++){const hw=highs.slice(i-n,i+n+1),lw=lows.slice(i-n,i+n+1);if(highs[i]===Math.max(...hw))levels.push({price:highs[i],type:'R'});if(lows[i]===Math.min(...lw))levels.push({price:lows[i],type:'S'});}const last=closes[closes.length-1];return{resistance:levels.filter(l=>l.type==='R'&&l.price>last).sort((a,b)=>a.price-b.price).slice(0,2),support:levels.filter(l=>l.type==='S'&&l.price<last).sort((a,b)=>b.price-a.price).slice(0,2)};}
function analyzePriceAction(data){try{const closes=(data.closes||[]).filter(Boolean),highs=(data.highs||[]).filter(Boolean),lows=(data.lows||[]).filter(Boolean),volumes=(data.volumes||[]).filter(Boolean),n=closes.length;if(n<20)return{score:0,signals:[]};let score=0,signals=[];const lb=Math.min(15,Math.floor(n/2)),rh=highs.slice(-lb),rl=lows.slice(-lb),mid=Math.floor(rh.length/2),fhH=Math.max(...rh.slice(0,mid)),shH=Math.max(...rh.slice(mid)),fhL=Math.min(...rl.slice(0,mid)),shL=Math.min(...rl.slice(mid));if(shH>fhH&&shL>fhL){score+=0.8;signals.push({text:'Price making higher highs and higher lows — bull trend structure confirmed',type:'bull'});}else if(shH<fhH&&shL<fhL){score-=0.8;signals.push({text:'Price making lower highs and lower lows — bear trend structure confirmed',type:'bear'});}else if(shL>fhL){score+=0.3;signals.push({text:'Higher lows forming — buyers defending dips',type:'bull'});}else if(shH<fhH){score-=0.3;signals.push({text:'Lower highs forming — sellers capping rallies',type:'bear'});}
const rs=Math.max(0,n-60),re=Math.max(rs+5,n-5);if(re>rs+4){const rc=closes[n-1],rhi=Math.max(...highs.slice(rs,re)),rlo=Math.min(...lows.slice(rs,re)),rv=volumes.slice(-5).reduce((a,b)=>a+b,0)/5,av=volumes.slice(-30).reduce((a,b)=>a+b,0)/30||1,vs=rv/av;if(rc>rhi*1.02&&vs>1.3){score+=1.2;signals.push({text:`Breakout above $${rhi.toFixed(2)} on ${(vs*100).toFixed(0)}% avg volume`,type:'bull'});}else if(rc>rhi*1.01){score+=0.6;signals.push({text:`Breaking above range ($${rhi.toFixed(2)})`,type:'bull'});}else if(rc<rlo*0.98&&vs>1.3){score-=1.2;signals.push({text:`Breakdown below $${rlo.toFixed(2)} on high volume`,type:'bear'});}else if(rc<rlo*0.99){score-=0.6;signals.push({text:`Breaking below range ($${rlo.toFixed(2)})`,type:'bear'});}}
if(n>=50){const yh=Math.max(...highs.slice(-Math.min(252,n))),yl=Math.min(...lows.slice(-Math.min(252,n))),rc=closes[n-1];if((yh-rc)/yh<0.05){score-=0.3;signals.push({text:`Within 5% of 52-week high ($${yh.toFixed(2)})`,type:'bear'});}else if((rc-yl)/Math.max(yl,0.01)<0.10){score+=0.3;signals.push({text:`Near 52-week low ($${yl.toFixed(2)}) — potential support`,type:'bull'});}}
if(n>=10){const l5=closes.slice(-5).reduce((a,b)=>a+b,0)/5,p5=closes.slice(-10,-5).reduce((a,b)=>a+b,0)/5;if(p5>0){const mp=(l5-p5)/p5;if(mp>0.04){score+=0.4;signals.push({text:`Strong momentum: +${(mp*100).toFixed(1)}% last 5 vs prior 5 candles`,type:'bull'});}else if(mp<-0.04){score-=0.4;signals.push({text:`Weak momentum: ${(mp*100).toFixed(1)}% last 5 vs prior 5 candles`,type:'bear'});}}}
return{score:Math.max(-1,Math.min(1,score)),signals};}catch(e){return{score:0,signals:[]};}}